### ISSUE TITLE
Tracking Page Views on Navigation Changes (js-application-appinsights sample)

### ISSUE THREAD

**Issue by patrickabel** [pnp/sp-dev-fx-extensions#114]
I have a solution similar to the [js-application-appinsights](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/js-application-appinsights) sample which uses a spfx extension (application customizer) to inject [Azure Application Insights](https://azure.microsoft.com/en-us/services/application-insights/) on modern SharePoint pages.

However, I have noticed that this current sample (as well as my solution) are **not capturing page views when navigating between pages on a modern SP site** because a full post-back and DOM load isn't occurring.

**How would you recommend a sample like this be extended to detect navigation changes?** I'm aware of the **navigatedEvent**, but that's not usable given how this sample injects JS into the page. Off hand, the only option I can see would be to trigger a page view to be captured on hash change.

Any guidance or updates to this sample would greatly appreciated! 

#### Category
- [x] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Page Views are tracked when navigating between pages in a modern SharePoint site.

#### Observed Behavior
Page Views are tracked by AAI when initially arriving on the page (window/DOM load) or when refreshing (F5) a page, but not when navigating between pages internally since the entire DOM isn't reloaded.

#### Steps to Reproduce
This behavior can be seen using the [sp-dev-fx-extensions/samples/js-application-appinsights](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/js-application-appinsights) sample.

**Comment by OmniFace** [comment]
We use the app-extensions "navigatedEvent" callback.  When moving between document or list library pages, this is triggered and can be used to reset your code.  Unfortunately, this is not triggered when doing a search, or returning to the home page.  Not sure if that is a bug or expected behavior at this point.

```javascript
this.context.application.navigatedEvent.add(this, function(eventArgs) { 
    // Your function
});
```

**Comment by patrickabel** [comment]
@OmniFace if you look at the sample I referenced, using this event callback isn't possible with the way that the AAI web-tracking code is being injected into the site. I'm really just looking for some guidance on how the Google Analytics and AAI samples can be leveraged/adapted given the changes to how the DOM loads/re-loads when navigating within a site.

**Comment by mwhelo** [comment]
@patrickabel I am having this same issue, have you found a solution to this yet?

**Comment by knalbandianbrightgrove** [comment]
@patrickabel @mwhelo 

Hi guys, I'm having the same issue, have you found any workaround?
I've tried to subscrive to dynamicDataProvider events, in order to notify the Documents library layout change (e.g. user click to folder), but no luck "@microsoft" make the property private.

May be we can help together to find proper way to fix this issue?

@VesaJuvonen any advise how we can solve it?

**Comment by patrickabel** [comment]
@knalbandianbrightgrove @mwhelo I haven't found a workaround yet on this issue. :/

**Comment by knalbandianbrightgrove** [comment]
@patrickabel sad :(

@VesaJuvonen We need your help! As the issue is major for us

**Comment by TuomasPakkanen** [comment]
Here's a Google Analytics SPFx extension that tracks also these page navigations:
http://sharepoint.handsontek.net/2017/12/21/how-to-add-google-analytics-to-the-modern-sharepoint/

I'm however looking for something similar for App Insights and I guess this sample still has this issue? @VesaJuvonen can you check it at some point?

**Comment by knalbandianbrightgrove** [comment]
@TuomasPakkanen the Google Analytics SPFx has the same issue!

**Comment by TuomasPakkanen** [comment]
> @TuomasPakkanen the Google Analytics SPFx has the same issue!

Seems that it does, after all. Haven't yet found a way to reliably monitor the modern sites on SPO. Hopefully there will be some update or fix to this navigation tracking soon.

**Comment by patrickabel** [comment]
@VesaJuvonen can you help here? We've got a number of samples here that no longer work here due to page-loading changes in SPO.

**Comment by sudharsank** [comment]
Hi Everyone,
Can you try the below code, the code also has the custom attributes added to the track.

```
let appInsightsScript: string = `var appInsights=window.appInsights || function (config) {
    function s(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } } var t = { config: config }, r = document, f = window, e = "script", o = r.createElement(e), i, u; for (o.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", r.getElementsByTagName(e)[0].parentNode.appendChild(o), t.cookie = r.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace"]; i.length;)s("track" + i.pop()); return config.disableExceptionTracking || (i = "onerror", s("_" + i), u = f[i], f[i] = function (config, r, f, e, o) { var s = u && u(config, r, f, e, o); return s !== !0 && t["_" + i](config, r, f, e, o), s }), t
      }({
          instrumentationKey: "` + this.properties.appInsightsKey + `"
      });
    window.appInsights = appInsights;
    appInsights.trackPageView(document.title, window.location.href, { UserTitle: "` + this.context.pageContext.user.displayName + `", UserEmail: "` + this.context.pageContext.user.email + `", UserLoginName: "` + this.context.pageContext.user.loginName + `" });`;

  let script = document.createElement("script");
  script.type = "text/javascript";
  script.appendChild(document.createTextNode(appInsightsScript));

  document.head.insertAdjacentElement("beforeend", script);
```

**Comment by sudharsank** [comment]
Hi Everyone,
I think I found the solution, try the below and let me know
Install the following modules
1. **@microsoft/applicationinsights-react-js**
2. **@microsoft/applicationinsights-web**
3. **history**

Copy the below code to **OnInit** method
```
const browserHistory = createBrowserHistory({ basename: '' });
    var reactPlugin = new ReactPlugin();
    var appInsights = new ApplicationInsights({
      config: {
        autoTrackPageVisitTime: true,        
        maxBatchInterval: 0,
        disableFetchTracking: true,
        disableAjaxTracking: true,
        enableAutoRouteTracking: true,
        instrumentationKey: `${this.properties.appInsightsKey}`,
        extensions: [reactPlugin],
        extensionConfig: {
          [reactPlugin.identifier]: { history: browserHistory }
        }
      }
    });
    appInsights.loadAppInsights();
appInsights.trackPageView({
      name: document.title, uri: window.location.href,
      properties: {
        ["CustomProps"]: {
          WebAbsUrl: this.context.pageContext.web.absoluteUrl,
          WebSerUrl: this.context.pageContext.web.serverRelativeUrl,
          WebId: this.context.pageContext.web.id,
          UserTitle: this.context.pageContext.user.displayName,
          UserEmail: this.context.pageContext.user.email,
          UserLoginName: this.context.pageContext.user.loginName
        }
      }
    });
```
You can track all the react routing. Please refer the below link for more details
https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript
Happy Coding...

**Comment by mohsinhere** [comment]
> Hi Everyone,
> I think I found the solution, try the below and let me know
> Install the following modules
> 
> 1. **@microsoft/applicationinsights-react-js**
> 2. **@microsoft/applicationinsights-web**
> 3. **history**
> 
> Copy the below code to **OnInit** method. I have also appended some of the properties that can be used for the reports.
> 
> ```
> const browserHistory = createBrowserHistory({ basename: '' });
>     var reactPlugin = new ReactPlugin();
>     var appInsights = new ApplicationInsights({
>       config: {
>         autoTrackPageVisitTime: true,        
>         maxBatchInterval: 0,
>         disableFetchTracking: true,
>         disableAjaxTracking: true,
>         enableAutoRouteTracking: true,
>         instrumentationKey: `${this.properties.appInsightsKey}`,
>         extensions: [reactPlugin],
>         extensionConfig: {
>           [reactPlugin.identifier]: { history: browserHistory }
>         }
>       }
>     });
>     appInsights.loadAppInsights();
> appInsights.trackPageView({
>       name: document.title, uri: window.location.href,
>       properties: {
>         ["CustomProps"]: {
>           WebAbsUrl: this.context.pageContext.web.absoluteUrl,
>           WebSerUrl: this.context.pageContext.web.serverRelativeUrl,
>           WebId: this.context.pageContext.web.id,
>           UserTitle: this.context.pageContext.user.displayName,
>           UserEmail: this.context.pageContext.user.email,
>           UserLoginName: this.context.pageContext.user.loginName
>         }
>       }
>     });
> ```
> 
> You can track all the react routing. Please refer the below link for more details
> https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript
> 
> I have also added a new extension to the PnP Samples, which will track the SPA pages which inludes news post pages in SharePoint online. Below is the URL, give it a try and let me know
> https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/js-application-appinsights-advanced
> 
> Happy Coding...

Hi,

Does this work fine for you? I'm using a similar solution... But now my Sharepoint Routing itself fails. I have raised an issue in app insights library... 

https://github.com/microsoft/ApplicationInsights-JS/issues/1294

**Comment by sudharsank** [comment]
Hi @mohsinhere, have you tried the extension that I had mentioned in my reply. Please feel free to go through the code. It works fine for me. I had tested with the out-of-box news items.

**Comment by mohsinhere** [comment]
@sudharsank  Thanks for the quick response... Yes, I'm using all the packages that you mentioned. Still, it breaks for some reason with error 
**Uncaught RangeError: Maximum call stack size exceeded**

I tried your code to see if it makes any difference.
```
const browserHistory = createBrowserHistory({basename: '' });
      var reactPlugin = new ReactPlugin();
      var appInsights = new ApplicationInsights({
      config: {
        autoTrackPageVisitTime: true,        
        maxBatchInterval: 0,
        disableFetchTracking: true,
        disableAjaxTracking: true,
        enableAutoRouteTracking: true,
        instrumentationKey: key,
        extensions: [reactPlugin],
        extensionConfig: {
          [reactPlugin.identifier]: { history: browserHistory }
        }
      }
    });
    appInsights.loadAppInsights();
    appInsights.trackPageView({
      name: document.title, uri: window.location.href,
      properties: {
        ["CustomProps"]: {
          WebAbsUrl: this.context.pageContext.web.absoluteUrl,
          WebSerUrl: this.context.pageContext.web.serverRelativeUrl,
          WebId: this.context.pageContext.web.id,
          UserTitle: this.context.pageContext.user.displayName,
          UserEmail: this.context.pageContext.user.email,
          UserLoginName: this.context.pageContext.user.loginName
        }
      }
    });
```
