### ISSUE TITLE
trigger a logger when a modern page "Published"

### ISSUE THREAD

**Issue by sabitertan** [pnp/sp-dev-fx-extensions#172]
## Category

- [X] Question
- [ ] Bug
- [ ] Enhancement
I would like to trigger a logger when a modern page "Published". 
I am trying to figure out how I can listen "Published" event on Publishing Modern Pages.
I am trying to use @microsoft/sp-core-library::ServiceScope.consume and I am not sure if this is a good way to go.
Can you provide an example to listen changes on page-state or state-manager?
Thanks!!

**Comment by hugoabernier** [comment]
@sabitertan I'll go ahead and close this issue as it appears to relate to general SPFx development. 

If you still need help with this, please open a new issue at https://aka.ms/spdev-issues. This issue list is intended for issues related to samples in this repository.
