### ISSUE TITLE
Breadcrumb not working on modern team site

### ISSUE THREAD

**Issue by TaurahSP** [pnp/sp-dev-fx-extensions#190]
I have deployed the breadcrum package to the appcatalogue and on developer site with modern pages the latter works fine. I am testing with a modern team site but the extension is not showing up and there is no error.

**Comment by hugoabernier** [comment]
Closing this issue as incomplete.

If you're still experiencing this issue, please open a new issue. If you do, please take the time to fill the issue template provided so that we can get you the help you deserve.
