### ISSUE TITLE
Convert to PDF

### ISSUE THREAD

**Issue by memsim1010** [pnp/sp-dev-fx-extensions#191]
@anoopt 
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Able to run 'gulp build' per Read Me instructions within "sp-dev-fx-extensions\samples\js-command-convert-to-pdf\ConvertToPDFRequest"

## Observed Behavior
Returned:
sp-dev-fx-extensions\samples\js-command-convert-to-pdf\ConvertToPDFRequest>gulp
build
[11:06:32] Local gulp not found in ~\sp-dev-fx-extensions\samples\js-command-convert-to-pdf\ConvertToPDFRequest
[11:06:32] Try running: npm install gulp

I ran npm install gulp

Error observed: 
sp-dev-fx-extensions\samples\js-command-convert-to-pdf\ConvertToPDFRequest>gulp
build
[11:07:42] No gulpfile found

## Steps to Reproduce
Navigate to ./ConvertToPDFRequest) in Visual studio and build it.

Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
@memsim1010 try running `npm i` from the root folder of the project (I.e. one level up) then `gulp serve`.

Let us know if you solved this issue.
