### ISSUE TITLE
onListViewUpdated Called many times

### ISSUE THREAD

**Issue by enti333** [pnp/sp-dev-fx-extensions#210]
- [x] Question
- [x] Bug
- [ ] Enhancement

Hello. I have this peace of cod 
`@override
  public onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters): void {
    const compareOneCommand: Command = this.tryGetCommand('DATAIMPORT');

    if (compareOneCommand) {
      compareOneCommand.visible = false;
      if (window.location.href.indexOf("hr/Lists/Concediu%20Angajati/") > -1) {
        sp.web.siteGroups.getByName("Import Admin").users.getByEmail(this.properties.email).get().then(rs => {
          compareOneCommand.visible = true;
        }).catch(error => {
          compareOneCommand.visible = false;
        });
      }
    }
  }`

The first problem is it doesn't work....I have debug it and everything is OK but the problem is that call is asynch and visible is always set to false....Can I make this type of call in listviewupdates...

The second problem is that my code is called maybe 4-5 times ...I can say hat everything in this method is called many times...Why is this?

Thank you very much for any help.

**Comment by hugoabernier** [comment]
@enti333 did you ever resolve this issue?

This issue list is intended for issues related to extension samples in this repo. If you're still experiencing this issue, feel free to open a new issue at https://aka.ms/spdev-issues
