### ISSUE TITLE
Extension not loading in one tenant

### ISSUE THREAD

**Issue by DanishIslam07** [pnp/sp-dev-fx-extensions#214]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Extension should be visible on command bar for document library

## Observed Behavior

Promise with no error callback:undefined error in console.

## Steps to Reproduce

I tried even basic extension following the steps here [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api ) but not working on one tenant.

I tried the same extension on 3 other tenants both via debug method and production package method, it works. It is not working only on one tenant, Is there any configuration missing on tenant?

I also submitted this issue on technet forum [https://social.technet.microsoft.com/Forums/en-US/81c679fc-4d44-49a9-b9b7-1fde042ef1fd/sharepoint-framework-extension-not-loading-in-one-tenant?forum=onlineservicessharepoint](https://social.technet.microsoft.com/Forums/en-US/81c679fc-4d44-49a9-b9b7-1fde042ef1fd/sharepoint-framework-extension-not-loading-in-one-tenant?forum=onlineservicessharepoint) but no luck as of now.

Please advise and help.

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
@DanishIslam07 did you ever resolve this issue?

I'll close it as this issue list is intended for issues related to samples in this repository. If you're still experiencing issues, feel free to open a new issue at https://aka.ms/spdev-issues
