### ISSUE TITLE
copy direct link does not work

### ISSUE THREAD

**Issue by honb** [pnp/sp-dev-fx-extensions#216]
in example, copy direct link does not work. The problem is el.select() does not work, the same code working fine outside SP extension.
Do you guys have any idea?

I meant copy text to clipboard

**Comment by hugoabernier** [comment]
Closing this issue as incomplete.

If you're still experiencing this issue, feel free to open a new issue. When you do, please take the time to fill the issue template that is provided so that we can help you accordingly.
