### ISSUE TITLE
Getting an error with ListViewExtender

### ISSUE THREAD

**Issue by kachihro** [pnp/sp-dev-fx-extensions#219]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

Have created a brand new SPFX project (v1.8) and chosen a listview extender - with the Command_one and Command_two buttons.

## Observed Behavior

Buttons do not show, message within console ;

_Uncaught Error: There is no operation handler registered for '{"operation_3":["getItems_1","spField_306"]}'._

## Steps to Reproduce

* Brand new project
* Extension project

gulp serve

**Comment by hugoabernier** [comment]
@kachihro did you ever resolve this issue?

I'll go ahead and close this issue as this issue list is intended for issues related to the samples in this repository. If you're still having problems, feel free to open a new issue at https://aka.ms/spdev-issues
