### ISSUE TITLE
Can react-application-tenant-global-navbar spfx part be used for SharePoint 2019 On Premise

### ISSUE THREAD

**Issue by bumblebee333** [pnp/sp-dev-fx-extensions#228]
## Category

- [X] Question
- [ ] Bug
- [ ] Enhancement

One of my clients has a requirement to customize the navigation menu for a modern site (SP 2019 onprem). I was wondering if this react spfx app - react-application-tenant-global-navbar  -  can be used for SharePoint 2019 On Prem installation.

Any feedback is appreciated?
Thanks
R

**Comment by hugoabernier** [comment]
@bumblebee333 according to [this article](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility), you can use extensions on SP 2019 as long as your solution uses SPFx 1.4.1 or lower. 

You may have to create a new extension using `yo @microsoft/sharepoint` using SPFx 1.4.1 and replicate the functionality you're looking for.

I hope this helps?
