### ISSUE TITLE
ListView Command Set doesn't refresh this.context.pageContext.list when navigate to a different library

### ISSUE THREAD

**Issue by ikmoss** [pnp/sp-dev-fx-extensions#245]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

In ListView Command Set extension, **this.context.pageContext.list** should be refreshed when navigating to a different library.

## Observed Behavior

this.context.pageContext.list within ListView Command Set extension doesn't always refresh the data when a user navigates to a different library. My command extension solution relies on this information to show a different set of actions for different libraries but it didn't work because this.contex.PageContext.List doesn't get updated when a user navigates to a different library.

## Steps to Reproduce

1. Go to a library1
2. Select an item
3. Click the list command menu
> Prints library1
4. Switch to library2 by clicking from the left-hand navigation menu
5. Select an item
6. Click the list command menu
> Prints library1 << It should print library2

Example code:
```javascript
 @override
   public onExecute(event: IListViewCommandSetExecuteEventParameters): void {
      console.log(this.context.pageContext.list.title);
   }
```
Output:
Library1
Library1

**Comment by PiotrNSmartlogic** [comment]
I also have this problem. I noticed that only first entry to the library after page refresh has a correct context. 

My steps:
1. Refresh page 
2. Go to library1 (CommandSet's constructor is triggered, context in events is correct)
3. Switch to library2 (CommandSet's constructor is triggered, context in events is correct)
4. Switch back to library1 (constructor is not triggered, context is incorrect, events are hadled by object created for library2)

**Comment by hugoabernier** [comment]
@ikmoss did you ever resolve this issue?

I'll go ahead and close it as this issue list is intended for issues related to extension samples in this repository.

If you still need help with this, please visit https://aka.ms/spdev-issues

**Comment by ikmoss** [comment]
> @ikmoss did you ever resolve this issue?
> 
> I'll go ahead and close it as this issue list is intended for issues related to extension samples in this repository.
> 
> If you still need help with this, please visit https://aka.ms/spdev-issues

I have logged MS Premiere support - they confirmed it and know how to replicate this issue and will work on the issue with Product team.

**Comment by PravinD5989** [comment]
@ikmoss @hugoabernier @PiotrNSmartlogic I also have this problem. Did you find some resolution for this issue.
