### ISSUE TITLE
Looking for To Trigger Notifications for Renewal dates || SharePoint 2013 Column

### ISSUE THREAD

**Issue by tejasthite** [pnp/sp-dev-fx-extensions#251]
Hi All, I am looking for Trigger Notifications for Renewal Dates for a SharePoint Column on SharePoint 2013 Using Microsoft Flow but for some reason, they aren't working correctly - any help will be greatly appreciated.

Thank you.

**Comment by hugoabernier** [comment]
Closing this issue as it does not relate to samples in this repository.

If you're still experiencing issues, please feel free to open a new issue at https://aka.ms/spdev-issues
