### ISSUE TITLE
Controlling order of execution of Application Customizers ?

### ISSUE THREAD

**Issue by kmprasad4u** [pnp/sp-dev-fx-extensions#282]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

I have created an extension which makes use of the top place holder and display additional menus in the site.  Now I am in need of creating another extension that conditionally displays notifications/announcements in the top place holder region. A separate place holder element is getting created for both the extensions. However I want the notifications to be always present at top of the page, and I am not seeing any way to control that. Is there any way we could handle this scenario ?

**Comment by ValerasNarbutas** [comment]
hey @kmprasad4u 
description is a bit not clear, maybe you could share repo or some visualisation of what you want to achieve?

**Comment by kmprasad4u** [comment]
Here is a simplified version...

![AppCustomizerOrder](https://user-images.githubusercontent.com/48886361/75567329-5c0a2c00-5a77-11ea-9bd7-7e5573f341a5.PNG)

Need the "notification" to be always present at top, irrespective of which customizer loads first.

**Comment by sudharsank** [comment]
Hi @kmprasad4u 
Can you make it both combined in a single application customizer. You can design the notification component on the top followed by the menu. So you don't have to worry about the loading sequence.

**Comment by kmprasad4u** [comment]
Yes that is what we are doing for now as we have control over both solutions. There may be instances where that may not be true.

**Comment by hugoabernier** [comment]
@kmprasad4u did you ever resolve this issue?

I'll go ahead and close this issue as it appears (somewhat) answered. If you still need help with this, please open a new issue.
