### ISSUE TITLE
Use OOB Context Menu in SPFx List View

### ISSUE THREAD

**Issue by spvjebaraj** [pnp/sp-dev-fx-extensions#284]
Hi,

I am working in SPFx project with custom PnP controls like ListView, Property Pane Multi Selection, Render Field etc. In that, I want to use the OOB context menu which is available in any of document libraries.

Is it possible to use the OOB in our custom solution? Please suggest.

**Comment by hugoabernier** [comment]
@spvjebaraj did you ever resolve this issue?

This issue list is intended for issues related to samples in this repository. If you're still experiencing issues, please feel free to open a new issue at aka.ms/spdev-issues
