### ISSUE TITLE
When I install this extensions, something error happened

### ISSUE THREAD

**Issue by hilfiger1014** [pnp/sp-dev-fx-extensions#291]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

When I attempt to install this sample for my testing, I ran into some problems during installation. I list out the error message as follows:: just wondering how to fix it.?

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19464 silly saveTree +-- @types/chai@3.4.34
19464 silly saveTree +-- @types/es6-promise@0.0.33
19464 silly saveTree +-- @types/mocha@2.2.38
19464 silly saveTree +-- @types/webpack-env@1.13.1
19464 silly saveTree +-- ajv@5.2.5
19464 silly saveTree +-- gulp@3.9.1
19464 silly saveTree `-- tslint-microsoft-contrib@5.0.3
19465 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
19465 verbose stack     at res.buffer.catch.then.body (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15)
19465 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
19466 verbose statusCode 404
19467 verbose pkgid event-stream@3.3.6
19468 verbose cwd C:\sp-dev-fx-extensions-master\samples\react-command-share-pnpjs
19469 verbose Windows_NT 10.0.17763
19470 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
19471 verbose node v10.17.0
19472 verbose npm  v6.11.3
19473 error code E404
19474 error 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
19475 error 404
19476 error 404 'event-stream@3.3.6' is not in the npm registry.
19477 error 404 You should bug the author to publish it (or use the name yourself!)
19478 error 404 It was specified as a dependency of 'gulp-connect'
19479 error 404 Note that you can also install from a
19480 error 404 tarball, folder, http url, or git url.
19481 verbose exit [ 1, true ]

**Comment by hugoabernier** [comment]
Closing this issue as incomplete. If you're still experiencing this issue, please take the time to fill the new issue template that's provided so we can help you accordingly.
