### ISSUE TITLE
SPFx Application Customize is not installed in multiple sub sites

### ISSUE THREAD

**Issue by dips365** [pnp/sp-dev-fx-extensions#300]
## Business Requirement
We need to change the SharePoint Site Logo redirect URL. When user click on the Logo from sub site then it should redirected to the site collection landing page.

To achieve this functionality we developed a application customizer and added below code in to it.

```typescript
 public onInit(): Promise<void> {

    Log.info(LOG_SOURCE, `Initialized ${strings.Title}`);

    $(document).ready(() => {
      console.log("Sample");
      let URL :string  = this.context.pageContext.site.absoluteUrl.toString();
      console.log($('[class*=logoWrapper]'));
      $('[class*=logoWrapper]').attr("href",URL);
      console.log(this.context.pageContext.site.absoluteUrl);
    });
    //
    return Promise.resolve();
  }
```

## Category

- [ ] Question
- [x] Bug
- [x] Enhancement
- [ ] Sample request

## Expected or Desired Behavior

When we installed the application in site or sub site , Site Logo Redirected Link with be change to site collection URL.

## Observed Behavior
We observed that the app is installed in one sub site successfully and when i check the URL of site logo it is set as expected.

When we try to install application customizer in another sub site then it raised the error as below.

> **A different version of this App is already installed with the same version number. You need to delete the app from the site and the site recycle bin to install this version**

Application customizer  installed in sub site "Sample Team Site" which is created from Team SIte(No Office 365 connected Group)

![WebpartChange12](https://user-images.githubusercontent.com/40450958/78764825-1897bd00-7955-11ea-829f-f93b54ac3b9f.gif)

When i try to install app in different sub site under the same site collection.
Sub Site Name : Sample Test 2

![WebpartChange1](https://user-images.githubusercontent.com/40450958/78765033-64e2fd00-7955-11ea-8eb6-af57f8486243.gif)

## Code Version
> Package.json
```json
{
  "name": "change-site-logo-url",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/decorators": "1.10.0",
    "@microsoft/sp-application-base": "1.10.0",
    "@microsoft/sp-core-library": "1.10.0",
    "@microsoft/sp-dialog": "1.10.0",
    "@types/es6-promise": "0.0.33",
    "@types/webpack-env": "1.13.1",
    "jquery": "^3.4.1"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.10.0",
    "@microsoft/sp-tslint-rules": "1.10.0",
    "@microsoft/sp-module-interfaces": "1.10.0",
    "@microsoft/sp-webpart-workbench": "1.10.0",
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}
```

>client-side-extension-manifest.schema.json

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx/client-side-extension-manifest.schema.json",

  "id": "632c2669-f1f8-4628-b092-377b4a46e4d2",
  "alias": "ChangeSiteLogoUrlApplicationCustomizer",
  "componentType": "Extension",
  "extensionType": "ApplicationCustomizer",

  // The "*" signifies that the version should be taken from the package.json
  "version": "*",
  "manifestVersion": 2,

  // If true, the component can only be installed on sites where Custom Script is allowed.
  // Components that allow authors to embed arbitrary script code should set this to true.
  // https://support.office.com/en-us/article/Turn-scripting-capabilities-on-or-off-1f2c515f-5d7e-448a-9fd7-835da935584f
  "requiresCustomScript": false
}
```

>package-solution.schema.json

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "change-site-logo-url-client-side-solution",
    "id": "c9046753-020d-4e80-ab92-14b79c620264",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "isDomainIsolated": false,
    "features": [
      {
        "title": "Application Extension - Deployment of custom action.",
        "description": "Deploys a custom action with ClientSideComponentId association",
        "id": "759cd2c5-7756-4259-ad68-33b598e49f95",
        "version": "1.0.0.0",
        "assets": {
          "elementManifests": [
            "elements.xml",
            "ClientSideInstance.xml"
          ]
        }
      }
    ]
  },
  "paths": {
    "zippedPackage": "solution/change-site-logo-url.sppkg"
  }

 }
```

## Steps to Reproduce

Create Sample Application customizer and deploy it in app catalogs
Create a multiple sub sites under same site collection.
Install app in multiple sub sites.

## Help
Can anyone help me out how can i resolve this issue? I don't want to upload a same app with multiple versions.

Thanks in advance !!

 **Sharing is caring.**

**Comment by sudharsank** [comment]
Hi @dips365 
From the above screenshot, it is clear that the app is installed on the site where you are trying to add it again. The error throws on the **version**. Try to empty your **recycle bin** and the **second stage recycle bin** and then try to add the app again. Let us know if you encounter any issues.

**Comment by dips365** [comment]
@sudharsank 
I tried it all the way.
When i installed Application Customizer in Site collection and i have not deleted so it is not in recycle bin.
Now when i trying to install the same application customizer to Sub site of that site collection it shows me error.

**Comment by sudharsank** [comment]
Hi @dips365 
I have a site named **/sites/ModernDev** and i have a separate site collection **App Catalog**. I had uploaded the extension app to the site collection app catalog, when I tried to add the app to the above mentioned site, it throws me the same error that you had mentioned. The only think I did was to clear the already deleted app from the site recycle bin and it automatically started installing the app on the site.

**Comment by dips365** [comment]
@sudharsank 
Please follow below steps to reproduce the issue.
Reproduce Scenario 1: 
1. Take any site collection called /sites/test
2. Add Application extension in site collection and it work deployed successfully.
3. Now create a sub site in /sites/test/sub1
4. Now try to add application extension and it throws error.

Reproduce Scenario 2:
1. Create a sub site  called sites/test/sub1
2. Install app extension on sub site (Sub1) and it is successfully installed.
3. Create a sub site called sites/test/sub2
4. Try to install application extension in second subsite and it throws error.

Questiton:
Can i add application extension in multiple sub sites under same site collection?

**Comment by sudharsank** [comment]
@dips365 
I tried the scenarios that you had mentioned and it all works fine. Yes you can add the extension in the subsites and there shouldn't be any problem on that.
FYI, I am using **Site Collection App Catalog** not the tenant wide app catalog.
My suggestion is to uninstall the extension in the site collection and in subsites if it is installed already, clean the 2 stages of recycle bin in the site collection and subsites. Then, try installing the extension again in the site collection followed by the sub sites or directly on the sub sites.
Let me know if you encounter any issues.

**Comment by prabhu8323** [comment]
I am also facing same issue. 

Scenario to reproduce:
- Deployed the Application customizer in Global App Catalog site.
- Installed the App in Site Collection and sub site in it.
- Created the new subsite in this site collection
- It throws the error

Please suggest if we have any concrete solution.

**Comment by adityapatil1989** [comment]
@dips365  : did you guys get any resolution for this. we too have one externsion deployed across tenant and can not added to sub sites .  it only gets added to newly created site collections
