### ISSUE TITLE
React-App-Announcements failing NPM Install

### ISSUE THREAD

**Issue by jok0** [pnp/sp-dev-fx-extensions#311]
## Expected or Desired Behavior
1) When running `npm install` all prereqs should install

## Observed Behavior
1) When running `npm install` the below output is generated:

 PS C:\Users\Joe\Documents\Sharepoint\sp-dev-fx-extensions\samples\react-app-announcements> `npm install `                 
>npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
> npm WARN deprecated fsevents@1.1.2: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> 
>  deasync@0.1.10 install C:\Users\Joe\Documents\Sharepoint\sp-dev-fx-extensions\samples\react-app-announcements\node_modules\deasync
>  node ./build.js
> 
> 
> C:\Users\Joe\Documents\Sharepoint\sp-dev-fx-extensions\samples\react-app-announcements\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   deasync.cc
>   win_delay_load_hook.cc
> c:\users\joe\documents\sharepoint\sp-dev-fx-extensions\samples\react-app-announcements\node_modules\nan\nan_maybe_43_in
> l.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..\src\deasync.cc) [C:\Users\
> Joe\Documents\Sharepoint\sp-dev-fx-extensions\samples\react-app-announcements\node_modules\deasync\build\deasync.vcxpro
> j]
>   c:\users\joe\appdata\local\node-gyp\cache\10.20.1\include\node\v8.h(3243): note: see declaration of 'v8::Object' (com
>   piling source file ..\src\deasync.cc)
> c:\users\joe\documents\sharepoint\sp-dev-fx-extensions\samples\react-app-announcements\node_modules\nan\nan.h(834): war
> ning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\deasync.cc) [C:\Users\Joe\Docum
> ents\Sharepoint\sp-dev-fx-extensions\samples\react-app-announcements\node_modules\deasync\build\deasync.vcxproj]
>   c:\users\joe\appdata\local\node-gyp\cache\10.20.1\include\node\node.h(176): note: see declaration of 'node::MakeCallb
>   ack' (compiling source file ..\src\deasync.cc)
> c:\users\joe\documents\sharepoint\sp-dev-fx-extensions\samples\react-app-announcements\node_modules\nan\nan.h(849): war
> ning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\deasync.cc) [C:\Users\Joe\Docum
> ents\Sharepoint\sp-dev-fx-extensions\samples\react-app-announcements\node_modules\deasync\build\deasync.vcxproj]
>   c:\users\joe\appdata\local\node-gyp\cache\10.20.1\include\node\node.h(169): note: see declaration of 'node::MakeCallb
>   ack' (compiling source file ..\src\deasync.cc)
> c:\users\joe\documents\sharepoint\sp-dev-fx-extensions\samples\react-app-announcements\node_modules\nan\nan.h(864): war
> ning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\deasync.cc) [C:\Users\Joe\Docum
> ents\Sharepoint\sp-dev-fx-extensions\samples\react-app-announcements\node_modules\deasync\build\deasync.vcxproj]
>   c:\users\joe\appdata\local\node-gyp\cache\10.20.1\include\node\node.h(162): note: see declaration of 'node::MakeCallb
>   ack' (compiling source file ..\src\deasync.cc)
> c:\users\joe\documents\sharepoint\sp-dev-fx-extensions\samples\react-app-announcements\node_modules\nan\nan.h(1473): wa
> rning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\deasync.cc) [C:\Users\Joe\Docu
> ments\Sharepoint\sp-dev-fx-extensions\samples\react-app-announcements\node_modules\deasync\build\deasync.vcxproj]
>   c:\users\joe\appdata\local\node-gyp\cache\10.20.1\include\node\node.h(176): note: see declaration of 'node::MakeCallb
>   ack' (compiling source file ..\src\deasync.cc)
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:191:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> gyp ERR! System Windows_NT 10.0.18363
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\Joe\Documents\Sharepoint\sp-dev-fx-extensions\samples\react-app-announcements\node_modules\deasync
> gyp ERR! node -v v10.20.1
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok
> Build failed
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! deasync@0.1.10 install: `node ./build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the deasync@0.1.10 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Joe\AppData\Roaming\npm-cache\_logs\2020-05-07T10_51_33_191Z-debug.log

Any help on this would be great.  I have tried to debug the issues myself and also ran the `npm install --global --production windows-build-tools
` command prior.

Thanks

**Comment by hugoabernier** [comment]
@jok0 this smells like a version incompatibility issue. Can you try to run [spfx doctor](https://pnp.github.io/office365-cli/cmd/spfx/doctor/) to see if there is an issue with your environment/project and report the results here?

**Comment by thespooler** [comment]
I also couldn't get it to build, that's part of why I made react-application-announcements. 
You might want to take a look.

**Comment by dandansoy2004** [comment]
HELP! Got error on the last step... 

Add-PnPCustomAction : A positional parameter cannot be found that accepts argument '-ClientSideComponentProperties={&quot;listName&quot;:&quot;Announcements&quot;, &quot;siteUrl&quot;:&quot;/sites/ComSite&quot;}'.

**Comment by dandansoy2004** [comment]
Can't make this work! Help..

Add-PnPCustomAction -Name "Announcements" -Title "Announcements" -Location "ClientSideExtension.ApplicationCustomizer" -ClientSideComponentId "dd7ec4fd-97aa-44c5-b6ad-87535862e0bf" -ClientSideComponentProperties="{&quot;listName&quot;:&quot;Announcements&quot;, &quot;siteUrl&quot;:&quot;/sites/Contoso&quot;}"

**Comment by ManjulaMasthanvali09** [comment]
this is not working at all

**Comment by hugoabernier** [comment]
@ManjulaMasthanvali09 feel free to open a ticket describing your issue and we'll try to help you.
