### ISSUE TITLE
npm install fails for react-field-toggle sample

### ISSUE THREAD

**Issue by jayaborra320** [pnp/sp-dev-fx-extensions#312]
Expectation: When running npm install all prereqs should install

Result:
npm WARN deprecated sp-pnp-js@2.0.8: Please migrate to the new libraries. More info: https://aka.ms/sp-pnp-js-deprecated
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\E0\source\sp-dev-fx-extensions\samples\react-field-toggle\node_modules\.staging\wrappy-3029caee\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\E0\source\sp-dev-fx-extensions\samples\react-field-toggle\node_modules\.staging\wrappy-3029caee\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\E0\source\sp-dev-fx-extensions\samples\react-field-toggle\node_modules\.staging\wrappy-3029caee\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\E0\source\sp-dev-fx-extensions\samples\react-field-toggle\node_modules\.staging\wrappy-3029caee\wrappy.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\E0\source\sp-dev-fx-extensions\samples\react-field-toggle\node_modules\.staging\xmlhttprequest-ssl-27e3948f\lib\XMLHttpRequest.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\E0\source\sp-dev-fx-extensions\samples\react-field-toggle\node_modules\.staging\@microsoft\sp-http-87d9bf3e\lib\index.js'
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@microsoft/decorators/-/decorators-1.0.1.tgz
npm ERR! 404
npm ERR! 404  '@microsoft/decorators@1.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'react-field-toggle'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by hugoabernier** [comment]
Closing this issue as incomplete.

In order to be able to help you, you'll need to fill the information requested in the new issue template.

We look forward to be able to help you with this.
