### ISSUE TITLE
Spfx field customizer for managed metadat field

### ISSUE THREAD

**Issue by anisiaalexandra** [pnp/sp-dev-fx-extensions#315]
Hi,

I have been trying to create a simple Spfx field customizer and tried to get related info with @pnp/sp-taxonomy. I constantly get the following issue and the field no longer get rendered. I cannot acces debug in this case. I have verified if it is the async calls but other async calls to Graph for example work. Do you have any idea of what can be wrong? Thank you in advance for your help.
Code extracts and error bellow:
Code:
`export default class MmdCustomizerFieldCustomizer
  extends BaseFieldCustomizer<IMmdCustomizerFieldCustomizerProperties> {

  @override
  public async onInit(): Promise<void> {
     const store: any = taxonomy.termStores.getByName("Taxonomy_mzHZJt6CKwm2h90n2KLRXg==");
    
    var term: ITerm = store.getTermById("${event.fieldValue.TermId}");

    this.properties.descr = await term.getDescription(1031);
    
    //var currentUser = (await this.getCurrentUserByGraph())["userPrincipalName"];
    //alert(currentUser);
  }`

Error:

listview-host-assembly_default_13c644876b8cb32e22df7c593449c80e.js:1 Uncaught (in promise) Error
    at r.t [as constructor] (listview-host-assembly_default_13c644876b8cb32e22df7c593449c80e.js:1)
    at new r (listview-host-assembly_default_13c644876b8cb32e22df7c593449c80e.js:1)
    at Function.e.buildErrorWithVerboseLog (listview-host-assembly_default_13c644876b8cb32e22df7c593449c80e.js:1)
    at Function.e.buildLoadComponentError (listview-host-assembly_default_13c644876b8cb32e22df7c593449c80e.js:1)
    at listview-host-assembly_default_13c644876b8cb32e22df7c593449c80e.js:1

**Comment by hugoabernier** [comment]
@anisiaalexandra this issue list is intended for issues related to samples in this repository.

I encourage you to open a new issue at aka.ms/spdev-issues so that we can get you the help you deserve.

**Comment by anisiaalexandra** [comment]
@hugoabernier Thank you for the answer and for pointing my in the right direction. 
For follow up I added this issue: [https://github.com/SharePoint/sp-dev-docs/issues/5816](here) .
