### ISSUE TITLE
ListView Command Set - Doesn't load always when navigate from home page

### ISSUE THREAD

**Issue by ikmoss** [pnp/sp-dev-fx-extensions#321]
NOTE: this issue exists in Targeted Released environment. I want to stop this change going into production!

## Expected or Desired Behavior
Listview command should appear all the time

## Observed Behavior
Listview command doesn't appear when navigated from home page from the left navigation link. Once Listview extension JS file is loaded/cached the problem doesn't appear but when you refresh the the home page using Ctrl+F5 key the problem appears.

## Steps to Reproduce

1. In main home page, Ctrl + F5 to refresh the page
2. Click the library/list link from left navigation
3. In the library/list, custom listview Command extension doesn't appear
4. In the library/list, Ctrl + F5 
5. Custom list view command appears after the refresh 

# Environment Details (*Development & Target environment*)

- **OS**: [e.g. Windows 10 ]
- **Target Environment**: [SharePoint Online]
- **Framework**: [Node.js v10]
- **Browser(s)**: [e.g. Chrome v79 | Chromium Edge v79]
- **Tooling**: [VS Code ]

# Additional context

**Comment by hugoabernier** [comment]
@ikmoss  this issue list is intended for issues related to samples in this repository.

I would recommend that you re-open this issue in the sp-dev-docs repository, where you'll most likely get the help you need.

Thank you!
