### ISSUE TITLE
Office UI Fabric CSS Override - Differences in Debug vs Deployed Package

### ISSUE THREAD

**Issue by TracyGH** [pnp/sp-dev-fx-extensions#322]
## Sample (which sample are you having trouble with)
https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/js-application-alert-message

## Authors
@sudharsank 

## Expected or Desired Behavior
I expect the height of the Extension container to be 30 pixels high.  I also expect the container heights to match, whether I'm running the project in debug mode or whether it is deployed to the tenant.  

## Observed Behavior
When running this project in Debug mode, the .ms-SPLegacyFabricBlock DIV wrapper inherits the 30 pixel height of the project DIV container (see below).
![image](https://user-images.githubusercontent.com/38665906/86825304-0dcbf180-c044-11ea-9f14-55fda4031dfa.png)

However once I deploy the project to the tenant, the .ms-SPLegacyFabricBlock DIV wrapper overrides the height with an inline value of 50 pixels (see below).  
![image](https://user-images.githubusercontent.com/38665906/86825467-3f44bd00-c044-11ea-99bd-a9fd0a9109c7.png)

I have reproduced this on both my development tenant and my client's tenant.  I suspect it may be related to [this GitHub issue](https://github.com/SharePoint/sp-dev-docs/issues/4911).

## Steps to Reproduce
1. Clone the Extensions sample repo
2. Run NPM install
3. Create an 'Alerts' list, per the ReadMe file
4. Update the serve.json file to point to a relevant page
5. Run gulp serve and observe the DOM dimensions
6. Now package/deploy the solution to the same tenant, and observe the differing DOM dimensions

# Environment Details (*Development & Target environment*)
Chrome
VSCode
Windows10
SharePoint Online

**Comment by sudharsank** [comment]
Hi @TracyGH,
When I showed the solution demo, I deployed to the comms site with height as **35px**. Can you please check the height in the below files.
1. PreallocatedTopPlaceholder height in **elements.xml** in sharepoint --> assets folder. If you are using tenant wide then please verify the **ClientSideInstance.xml** too.
2. height style in **GlobalAlerts.module.scss**

If the heights are same on the above mentioned files, there shouldn't be any problem on the SharePoint whether it is in debug mode or not.

![image](https://user-images.githubusercontent.com/10280385/86870755-8c3f9680-c10b-11ea-9cf9-32ede07d3b86.png)

Let me know if you have any clarifications.

**Comment by TracyGH** [comment]
Thanks @sudharsank,

I did not make any changes to the GlobalAlerts.module.css file from the repo, which is currently showing a height of 30 pixels (see below).  It looks like your .ms-SPLegacyFabricBlock DIV wrapper is overriding the container height with an inline value of 35 pixels, rather than 50.  If you take a look at the issue I referenced, it looks like there are different things going on from a Fabric UI perspective across different tenants.  
![image](https://user-images.githubusercontent.com/38665906/86944361-81c9d080-c0fc-11ea-9d94-7d104ecbcca1.png)

**Comment by sudharsank** [comment]
Hi @TracyGH 
I had updated the sample with more properties and issue fix. Raised a pull request to be merged with master dir. Please let me know once you had deployed the latest from the samples.
Let me know if you have any issues with the sample. Sorry for the inconvenience.

**Comment by sudharsank** [comment]
Hi @hugoabernier, you can assign this issue to me and I had already raised a pull request for the issue fix.

**Comment by OPIG** [comment]
Hi @sudharsank 

I'm using sp-office-ui-fabric-core in SPFx project, the css was load successfully in Dev Env, but can't be load in Pro Env.

I have import sp-office-ui-fabric-core in my scss file. and i can see the style in my scss file but no SPFabricCore.scss content in Pro Env.
@import '~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss';
