### ISSUE TITLE
URL mentioned on the page is not working

### ISSUE THREAD

**Issue by gauravgoyal5** [pnp/sp-dev-fx-extensions#323]
## Expected or Desired Behavior
The link http://dev.office.com/sharepoint should work which is mentioned here :
![image](https://user-images.githubusercontent.com/6926513/87002888-2ec54b80-c1d8-11ea-9fec-37e6cbf82cda.png)

## Observed Behavior
When clicking on the link, It is showing error :
This site can’t be reacheddev.office.com’s server IP address could not be found.

## Steps to Reproduce

1. Go to 'https://github.com/pnp/sp-dev-fx-extensions'
2. Click on 'http://dev.office.com/sharepoint' which is mentioned in right side.

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**: NA
- **Framework**: NA
- **Browser(s)**: ANY
- **Tooling**: NA
- **Additional details**: NA

**Comment by hugoabernier** [comment]
Thanks @gauravgoyal5, I've made the changes to solve this issue.
