### ISSUE TITLE
Bundling solution fails to 'collectLocalizedResources' on Azure DevOps

### ISSUE THREAD

**Issue by iMinion** [pnp/sp-dev-fx-extensions#327]
## Expected or Desired Behavior
Successful build when "gulp bundle --ship" command is ran on Azure DevOps

## Observed Behavior

On Azure DevOps, when I run gulp bundle --ship, it fails with the following error
![image](https://user-images.githubusercontent.com/6015582/90728057-deb2cc00-e2e1-11ea-9038-ca15e6893f4d.png)

## Steps to Reproduce

We've set up an Azure Build Pipeline with the following build order
1. Use Node 10.20.1
2. npm install
3. gulp clean
4. gulp bundle --ship
5. gulp package-solution --ship

![image](https://user-images.githubusercontent.com/6015582/90729971-f8094780-e2e4-11ea-967c-7d4b8979a58c.png)

# Environment Details (*Development & Target environment*)

- **OS**: [Windows 2019]
- **Target Environment**: [SharePoint Online]
- **Framework**: [Node.js v10]
- **Browser(s)**: [NA]
- **Tooling**: [SPFx v1.10.0]
- **Additional details**: The issue is not reproducible in my local environment. It happens only when I do it on Azure Dev Ops.

## Additional context
My config.json is as follows
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/config.2.0.schema.json",
  "version": "2.0",
  "bundles": {
    "resource-consent-web-part": {
      "components": [
        {
          "entrypoint": "./lib/webparts/resourceConsent/ResourceConsentWebPart.js",
          "manifest": "./src/webparts/resourceConsent/ResourceConsentWebPart.manifest.json"
        }
      ]
    }
  },
  "externals": {
    "jszip": {
      "path": "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.5.0/jszip.min.js",
      "globalName": "JSZip"
    },
    "jquery": {
      "path": "https://code.jquery.com/jquery-3.5.1.min.js",
      "globalName": "jQuery"
    },
    "devextreme/bundles/dx.all": {
      "path": "https://cdn3.devexpress.com/jslib/20.1.5/js/dx.all.js",
      "globalName": "DevExpress",
      "globalDependencies": [
        "jquery"
      ]
    }
  },
  "localizedResources": {
    "ResourceConsentWebPartStrings": "lib/webparts/resourceConsent/loc/resourceConsentWebPartStringValues.js",
    "appSettings": "lib/webparts/appSettings.js"
  }
}

**Comment by hugoabernier** [comment]
@iMinion this issue list is intended for issues related to samples in this repository. I would recommend that you open this issue with the sp-dev-docs repository, where you'll most likely get the help you need.

Thank you!

**Comment by iMinion** [comment]
Thank you @hugoabernier will check there!
