### ISSUE TITLE
react-command-qrcode: Dialog could not be shown

### ISSUE THREAD

**Issue by honb** [pnp/sp-dev-fx-extensions#335]
## Sample
https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/react-command-qrcode

## Expected or Desired Behavior
Dialog should be shown when clicking on command bar

## Observed Behavior
Dialog could not be shown (Error: The value for "domElement" must not be undefined)

## Steps to Reproduce
1. Clone: https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/react-command-qrcode
2. Update RegistrationId="101" in ClientSideInstance.xml & elements.xml
3. Package solutions
4. Upload into App Catalog
5. Go to home page of a site
6. From left navigation, click on a document library
7. Click on command bar to show dialog
![image](https://user-images.githubusercontent.com/26110193/95010340-b0e7d380-0652-11eb-890a-e04aa650e86d.png)

# Environment Details (*Development & Target environment*)

- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: [e.g. SharePoint Online]
- **Framework**: [e.g. Node.js v6/v8/v10/v12]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

## Additional context
Hit F5 then try to click ==> It works

**Comment by hugoabernier** [comment]
Hey @honb, I can't reproduce this problem. There is no `RegistrationId` in `ClientSideInstance.xml`.

Are you still running into this issue?
