### ISSUE TITLE
can we use states(react) in SPFx extensions ?  

### ISSUE THREAD

**Issue by sunnyEspireGit** [pnp/sp-dev-fx-extensions#337]
## Question :  I have a requirement where i need to :
 1. create a button on top header of page using SPFx extension,  
 2. after clicking on it should open a Panel,   
 3. inside that panel i want to create things we do in SPFx react webpart(creating 
    controls,setting their values create class/functional components) to perform
    further actions.

Can we do that (calling a class component where states are used in extensions) ?

**Please help with some related articles.**

**Comment by hugoabernier** [comment]
@sunnyEspireGit yes you can. Your rendered react elements are just like any other react components and can use state.

**Comment by sunnyEspireGit** [comment]
@hugoabernier : Could you please help me with any article of github project from where i can take reference ?

**Comment by hugoabernier** [comment]
@sunnyEspireGit here are some samples you may want to look at:
[react-application-machine-translations](react-application-machine-translations) uses an application extension to add a button to a page
[react-application-myfavourites](https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/react-application-myfavourites) adds buttons to pop open a panel.
[react-application-myfollowedsites](https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/react-application-myfollowedsites) adds a button outside of the placeholders. Microsoft may change the page structure at any time, which may break your application extension if you render controls outside of the placeholders. Rahul's example may still be useful if not exactly supported.
