### ISSUE TITLE
react-application-breadcrumb: File name to long to clone

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [pnp/sp-dev-fx-extensions#339]
## Sample (which sample are you having trouble with)
react-application-breadcrumb
## Authors
Elio Struyf (MVP, U2U, @eliostruyf)

## Expected or Desired Behavior
sp-dev-fx-extensions can be cloned under some sub folder

## Observed Behavior
samples/react-application-breadcrumb/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/components/mobilePreview/mobilePreviewHeaderBar/mobilePreviewDeviceTypeSelector/MobilePreviewDeviceTypeSelector.module.scss.d.ts.map: Filename too long

## Steps to Reproduce

1. Clone sp-dev-fx-extensions

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**: [e.g. SharePoint Server 2016 | SharePoint Server 2019 | SharePoint Online]
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v6/v8/v10/v12]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 | Visual Studio 2019]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by hugoabernier** [comment]
@DingmaomaoBJTU this is a common issue with Windows 10. Try cloning the repository on a really short file path. For example, I'll use: `c:\spfx\` or `c:\code` to workaround.

Unfortunately, the naming convention we use for samples tends to generate very long file names which results in the error in Windows.
