### ISSUE TITLE
React application announcements extension not working/loading in ie11 browser

### ISSUE THREAD

**Issue by vinaybangari1** [pnp/sp-dev-fx-extensions#345]
I downloaded the package and run npm install locally and globally in the project, the project build and deployed to our tenant successfully and working as expected in chrome and Firefox but the problem is not working/loading in IE11 browser, any idea or thoughts will be appreciated.

**Comment by thespooler** [comment]
If you're talking about react-application-announcements, sadly you might be out of luck. 

I did try IE and it is indeed broken, but I won't be the poor soul trying to fight IE debugger. A look at the console didn't show any error that was related to any custom code, only a `SCRIPT5009: 'exports' is undefined in activityMonitor.js (25,1)`, which is first-party.

Perhaps a polyfill might fill the gaps or something, but that's a long shot.

Also, you might want to take note of this announcement:
https://docs.microsoft.com/en-us/lifecycle/announcements/m365-ie11-microsoft-edge-legacy

Good luck and do let me know if you need help (non IE related).

**Comment by hugoabernier** [comment]
Closing this question as answered. Sadly, it is probably not the answer you wanted.

If you need any more help, please don't hesitate to create a new issue.
