### ISSUE TITLE
react-command-file-size-viewer - Issue with Manifest

### ISSUE THREAD

**Issue by Ramiz-Arshad** [pnp/sp-dev-fx-extensions#360]
## Sample (which sample are you having trouble with)
react-command-file-size-viewer

## Authors
@jquintozamora 

## Expected or Desired Behavior
After pulling the latest, running npm install and then gulp bundle, solution should build with no errors and run without any errors.

## Observed Behavior
Faced no error after gulp serve --nobrowser but After running facing error.

![image](https://user-images.githubusercontent.com/28856501/107606001-d199e880-6c45-11eb-8d52-7308687a1a75.png)

## Steps to Reproduce

1. Pull Repository
2. Change directory to react-command-file-size-viewer
3. npm install
4. gulp serve --nobrowser
5. Go to Document library.
6.  Add the following at the end of document library url.
`?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={"5f509a36-9998-4a5f-a5f4-b7d02d4f90b4":{"location":"ClientSideExtension.ListViewCommandSet"}}` 

# Environment Details (*Development & Target environment*)

OS: Windows 10
Target Environment: SharePoint Online
Node.js v10.23.0
Tooling VS Code

## Additional context
Followed the steps mentioned in [this](https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/react-command-file-size-viewer) sample.

**Comment by sudharsank** [comment]
Hi @Ramiz-Arshad the solution has been updated to the latest version and issue is verified too. Please take the latest and try it out and let us know if you got any issues.
