### ISSUE TITLE
Hi , this is about your react-application-breadcrumb which I deployed to a test tenant site collection. It works at the root site collection but for any subsites I need to manually add the app. Is there any way I can deploy to all the sub-sites withing the site collection? Also I noticed when I add the breadcrumb app to a subsite then the breadcrumb is duplicated

### ISSUE THREAD

**Issue by ctimoftey** [pnp/sp-dev-fx-extensions#369]
Thank you for your suggestion! Use the sections below to submit a suggestion ONLY if it's related to samples in this repo. If you have an issue or question about the SharePoint Framework or its documentation, please submit it at https://aka.ms/spdev-issues

- Suggestions that do not follow the below template will automatically be closed
- All ideas are welcome - let's build something together!
- This repo is maintained by volunteers (not Microsoft). Please be courteous and patient. 🙂
- Include sufficient details and context.
- If you have multiple suggestions please submit them separately so we can track resolution.
- Screenshots are always helpful (just paste any images right here in the suggestion)

DELETE EVERYTHING ABOVE AFTER READING - THANKS!

## Authors

> Because of the way this repository is configured, samples authors do not get a notification when you create an issue. *It makes it less likely for you to get your issue resolved or to get help*. For the section above **@mention any author of the sample**. The authors' GitHub handle can be found on the main sample documentation page, under the "solution" section. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

**Comment by hugoabernier** [comment]
Thanks for your issue, but in order to help you, we'll need you to fill the new issue template completely, with solution name, author, environment, etc.

I'll go ahead and close this issue as incomplete. Feel free to open a new issue with all the information requested.
