### ISSUE TITLE
breadcrumb gets duplicated at the subsite level when I add the breadcrumb app

### ISSUE THREAD

**Issue by ctimoftey** [pnp/sp-dev-fx-extensions#370]
[
![duplicate_breadcrumb](https://user-images.githubusercontent.com/80866261/111564406-e8f15780-8756-11eb-8f72-4bf542b9847c.JPG)
](url)

**Comment by hugoabernier** [comment]
Thanks for your issue, but in order to help you, we'll need you to fill the new issue template completely, with solution name, author, environment, etc.

I'll go ahead and close this issue as incomplete. Feel free to open a new issue with all the information requested.
