### ISSUE TITLE
unable to configure react-application-announcements

### ISSUE THREAD

**Issue by nilang-shah** [pnp/sp-dev-fx-extensions#390]
### Sample

https://github.com/pnp/sp-dev-fx-extensions/tree/main/samples/react-application-announcements

### Author(s)

@thespooler

### What happened?

I have followed all steps mentioned within this page https://github.com/pnp/sp-dev-fx-extensions/tree/main/samples/react-application-announcements under **Announcements list columns**, **Build and deploy and using PowerShell** but I am not able to make react-application-announcements application work.

I have to fix the few minor issues within PnPPowerShell before add customaction to add extension to my site as below. I also made sure list name is also "Site Announcements".

`Add-PnPCustomAction -Name "Announcements" -Title "Announcements" -Location "ClientSideExtension.ApplicationCustomizer" -ClientSideComponentId "dd7ec4fd-97aa-44c5-b6ad-87535862e0bf" -ClientSideComponentProperties "{`"listName`":`"Site Announcements`", `"siteUrl`":`"/sites/HubTest`"}"`

### Steps to reproduce

- It does work when I do **gulp serve** and append following query string after site url

 `?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={"dd7ec4fd-97aa-44c5-b6ad-87535862e0bf":{"location":"ClientSideExtension.ApplicationCustomizer","properties":{"listName":"Site%20Announcements","siteUrl":"/sites/ProjectHubTest"}}}`

![react-application-announcements-gulp-serve-1](https://user-images.githubusercontent.com/26605680/118682364-60cb1500-b7ce-11eb-8327-883365b9d450.JPG)

- However, it does not work after adding Add-PnPCustomAction , it does not work, it does not show any annoucements.

![react-application-announcements-2](https://user-images.githubusercontent.com/26605680/118681849-e9958100-b7cd-11eb-92a8-1a1cfc467ca2.JPG)

### Expected behavior

Announcement(s) banner should show up after adding announcements to Site Announcements list, as displayed in above image.

I will appreciate any help or suggestion on this.

Thank You,
Nilang

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### SPFx version

1.9.1

### Node.js version

v8.9.4

**Comment by thespooler** [comment]
Did you correctly escape that PowerShell string? The way it is pasted looks wrong, but it might just be GH issues messing it up. Otherwise, it looks like you're using the /sites/ProjectHubTest in one case and /sites/HubTest in the other.
You should look at your network traffic tab to see if any queries are 404 or looks wrong.

**Comment by nilang-shah** [comment]
Hi @thespooler, 

Thanks for your quick reply. I am using exact same URL "/sites/ProjectHubTest", for some reason I messed up while creating a bug, I am attaching image for both my PS command and Network traffic tab below.

**PowerShell**
![react-application-announcements-powershell](https://user-images.githubusercontent.com/26605680/118702856-7434ab00-b7e3-11eb-91e9-2c9e4f968fa3.JPG)


**Network Traffic Tab** - FYI, I sorted status by descending
![react-application-announcements-3](https://user-images.githubusercontent.com/26605680/118702634-2cae1f00-b7e3-11eb-9c7a-04dfc0f78a70.JPG)

Thank You,
Nilang

**Comment by nilang-shah** [comment]
Hi @thespooler , 

One thing I noticed when its working in debug mode with `gulp serve` and query string. it does return with 2 404 errors for react and react-dom as in below screenshot. 

![react and react-dom error](https://user-images.githubusercontent.com/26605680/118706414-549f8180-b7e7-11eb-9384-5d7304eedd8d.JPG)

However, while in regular mode its not working it does not give those 2 errors. 

So is it possible, when we use gulp-serve with query string, and allow loading unsafe script, may execute the script which otherwise does not allow in regular mode ? 

Thank You,
Nilang

**Comment by nilang-shah** [comment]
Hi @thespooler ,

I will appreciate any help or suggestion on this, so I can troubleshoot it further.

Thank You,
Nilang

**Comment by thespooler** [comment]
Any error in the console?

**Comment by nilang-shah** [comment]
Hi @thespooler ,

Screenshots I provided [above message](https://github.com/pnp/sp-dev-fx-extensions/issues/390#issuecomment-843444653) do contain errors in the console.

In reference with backticks, As PowerShell provided in readme did not work for me I have got reference from [Add-PnPCustomAction Example-2](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpcustomaction?view=sharepoint-ps#example-2) 

Thank You for all your help!

**Comment by thespooler** [comment]
Maybe, but they're not related to this webpart. 
The call stack only shows platform stuff.

**Comment by hugoabernier** [comment]
@nilang-shah it looks like the issue isn't related to the extension. 

I'll mark this issue as closed, but feel free to open a new issue so we can investigate further.
