### ISSUE TITLE
react-application-pva-bot

### ISSUE THREAD

**Issue by johanvandy** [pnp/sp-dev-fx-extensions#396]
### Sample

https://github.com/pnp/sp-dev-fx-extensions/tree/main/samples/react-application-pva-bot

### Author(s)

@hugoabernier  @bernierh @dmitryvorobyov

### Question

Hi all,

Am trying this extension as is. The only changes I made is the **pageUrl** in the serve.json file to point to one of our sites and not the default Contoso site.

I have not configured\added any Authentication (Adding Authentication Support was skipped by me).

If I try 'gulp serve' everything loads as expected and the bot is available but it is reporting **unable to connect**

![ChatBotErr](https://user-images.githubusercontent.com/44995057/121522712-ad80c500-c9f5-11eb-995f-79d4926d20f3.png)

I am thinking that I should add\configure my bot_id and tenant_id somewhere but I am not sure where?

Can you assist\guide please?

**Comment by hugoabernier** [comment]
Thanks @johanvandy for trying the sample. Can you confirm that you followed the instructions to find the `botId` and `tenantId` and added those to your updated `serve.json`? 

If you didn't, please do so and open a new **bug** ticket so we can diagnose the issue.

I'll go ahead and close this issue, as we'll need the environment details/repro steps to resolve this issue.

**Comment by johanvandy** [comment]
Thanks @hugoabernier 
I cannot find a placeholder for the the **botid** or **tenantid** in the serve.json file. Neither can I find any reference in the readme file to where they should be configured.
Below is a copy of my serve.json file.

`{
  "$schema": "https://developer.microsoft.com/json-schemas/core-build/serve.schema.json",
  "port": 4321,
  "https": true,
  "serveConfigurations": {
    "default": {
      "pageUrl": "https://xxxxx/sites/IntranetQA/SitePages/Chatbot-Test.aspx",
      "customActions": {
        "651e5ed0-c115-4301-beca-b36a6678d7bb": {
          "location": "ClientSideExtension.ApplicationCustomizer",
          "properties": {
            "testMessage": "Test message"
          }
        }
      }
    },
    "powerVirtualAgentsHost": {
      "pageUrl": "https://xxxxxx/sites/IntranetQA/SitePages/Chatbot-Test.aspx",
      "customActions": {
        "651e5ed0-c115-4301-beca-b36a6678d7bb": {
          "location": "ClientSideExtension.ApplicationCustomizer",
          "properties": {
            "testMessage": "Test message"
          }
        }
      }
    }
  }
}
`

I will go ahead and log a bug as suggested.
