### ISSUE TITLE
App package error when trying to deploy extension in the app catalog

### ISSUE THREAD

**Issue by moumen100** [pnp/sp-dev-fx-extensions#434]
### Sample

react-command-page-model-pnpjs

### Author(s)

VesaJuvonen

### What happened?

I have noticed error message after i upload the sppkg in the app catalog in both sharepoint online and sharepoint 2019 on-prem solutions 
below the error message 
![image](https://user-images.githubusercontent.com/31031378/146013923-596c28ac-9e25-42d5-9a59-50072c60d29c.png)

### Steps to reproduce

1. gulp bundle
2.gulp package-solution
3.deploy the sppkg in app catalog

### Expected behavior

.

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v8.9.4

**Comment by mohammadamer** [comment]
Hi @moumen100 
Have you implemented the steps in the Minimal Path to Awesome (the Powershell script that should add a column in Site Pages) ?
