### ISSUE TITLE
react-my-lists-notifications Why not using "sp-list-subscription"

### ISSUE THREAD

**Issue by tleclaire** [pnp/sp-dev-fx-extensions#444]
### Sample

react-application-my-lists-notifications

### Author(s)

@hugubarnier

### Question

Looking at the code, you are handling the notifications by using the graph api and Socket.io directly allthough there is a SPFx standard package "sp-list-subscription" available, which would at least eliminate the need for graph permissions.
So the question is: 
Why aren't you using sp-list-subscription for this sample and would that work as well?

Thanks
Thomas

**Comment by hugoabernier** [comment]
Hello @tleclaire, were you able to resolve this issue? 

I'll go ahead and close this, but if you have more questions, please do not hesitate to open a new issue and provide more information.
