### ISSUE TITLE
js-application-microsoft-clarity - 

### ISSUE THREAD

**Issue by Worrelpa** [pnp/sp-dev-fx-extensions#451]
### Sample

js-application-microsoft-clarity

### Author(s)

@joaoferreira

### Question

In the Video about Clarity Joao showed a fix for issues with heat maps in Clarity for SP Sites. Is there any further information on this fix and how it can be implemented? 

Thanks

**Comment by hugoabernier** [comment]
Hey @Worrelpa, were you able to resolve this issue? 

I'll go ahead and close this, but if you have more questions, please do not hesitate to open a new issue and provide more information.
