### ISSUE TITLE
The application customiser wouldn't remove from the site collection

### ISSUE THREAD

**Issue by saqis** [pnp/sp-dev-fx-extensions#462]
### Sample

https://github.com/pnp/sp-dev-fx-extensions/tree/main/samples/react-application-injectcss

### Author(s)

@hugoabernier

### What happened?

This extension was initially deployed to the whole tenancy (at the time of the installation) as a test and we never actually used it in any of site collections however we started experiencing the following issue recently and did some investigation.

A folder/document library gets shared with an external user and if the user accesses the folder/document library after the session is timed out (i.e. user has to re-authenticate) then the user gets the "External Sharing is disabled" error. The issue doesn't appear for the internal users.

We have contacted the Microsoft support and they have referred to the GitHub support for this project. 

### Steps to reproduce

We recently changed the settings of the app to disable it for any new site collection and created a new site collection (which didn't have this app installed) and the issue didn't appear for the external user. We enabled the app and the issue started appearing and even after the uninstalling the app, the issue still appears. 

### Expected behavior

The external users to be able to access the site (where this app is installed) without any issue (i.e. external sharing is disabled error) after the session is timed out.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

-

**Comment by hugoabernier** [comment]
This usually happens when you deploy the extension more than once on a site.

Take a look at https://www.peters.com/blog/sharepoint-online-sharepoint-framework-spfx-extensions-custom-action-cleanup/
