### ISSUE TITLE
Solution Deployment Error

### ISSUE THREAD

**Issue by Sharukh-maker** [pnp/sp-dev-fx-extensions#485]
### Sample

sp-dev-fx-extensions-main\samples\js-command-selecteditems-export

### Author(s)

none

### What happened?

Hi,
   I was trying to add this spfx-cmdex-export-items List command view extension to my tenant and i have deployed it successfully but when I am trying to select list item to export into excel then list command view extension is not visible on site.
Not sure where the issue?
    

### Steps to reproduce

1.gulp bundle --ship
2.gulp package-solution
3.Deploy solution in app catalog

### Expected behavior

I am expected that solution is working on my site when I am selected list items.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v14.15.0

**Comment by RobinP1** [comment]
I got the same error, creating the list manually fixed the problem.

**Comment by hugoabernier** [comment]
Closing this issue as it does not have any author and is not likely to get addressed.
