### ISSUE TITLE
react-application-news-ticker - 

### ISSUE THREAD

**Issue by priyaram51** [pnp/sp-dev-fx-extensions#486]
### Sample

react-application-news-ticker

### Author(s)

@AriGunawan

### Question

Hi

I have followed the steps to implement and deployed this solution to my site, but after that I cant see the News ticker running on the top of the page. Any idea what am missing here? The deployment steps are not mentioned so used my usual deployment method to my site.

**Comment by AriGunawan** [comment]
It seems that the last update (upgrade SPFx version to 1.14) didn't correctly implemented (missed readme, missed modules (react, react-dom, types, etc), changed ids, etc).
I've recreated the app using the latest SPFx and tested + deployed the app.
Hope the app works again for you.
*Please reinstall the app from fresh folder to make sure that you install the latest version (after my PR has been merged)
