### ISSUE TITLE
Adding form customizers as a category on the search page of the website 

### ISSUE THREAD

**Issue by martinlingstuyl** [pnp/sp-dev-fx-extensions#849]
### Sample

All form customizers

### Suggestion

The pnp extensions samples website has a search feature where a couple of categories are used:
Application Customizers, ListView Command Sets and Field Customizers.

Form Customizers are missing though. We do have one or two in the repo, so I think it would be good to include it.

![image](https://github.com/pnp/sp-dev-fx-extensions/assets/5267487/e362d89f-2e63-46fe-babe-de052b15f8e7)
 
I'm not sure where the website repo is, otherwise I'd possibly submit a PR for this.

### Are you willing to help?

Yes

**Comment by martinlingstuyl** [comment]
Extra interesting, I've PR'ed one Form Customizer just now. I've found one other in the repo:
[React Form Customizer](https://github.com/pnp/sp-dev-fx-extensions/tree/main/samples/react-formcustomizer-customers)

But I cannot find it using search on the website.

**Comment by martinlingstuyl** [comment]
@hugoabernier, would you know where I can submit a PR for this?

**Comment by martinlingstuyl** [comment]
@hugoabernier, @VesaJuvonen, any of you an idea about this issue? I created two form customizer samples which don't show up on the website because of this category thing. I'd like to fix it but don't know where..

**Comment by martinlingstuyl** [comment]
> @hugoabernier, @VesaJuvonen, any of you an idea about this issue? I created two form customizer samples which don't show up on the website because of this category thing. I'd like to fix it but don't know where..

Pinging this again @hugoabernier :-)

**Comment by hugoabernier** [comment]
@martinlingstuyl thanks for pinging again. As long as the `sample.json` for the sample says that it is a `SPFX-FORM-EXTENSION` under `categories`, the sample will show if the form extension filter at aka.ms/spfx-webparts.

```json
"categories": [
      "SPFX-FORM-EXTENSION"
    ],
```
If you find a sample that's missing, feel free to submit a PR for the sample.json, or let me know the specific sample.

I hope this helps?

**Comment by hugoabernier** [comment]
Closing issue as solved, but please open individual issues if you find missing samples.

**Comment by martinlingstuyl** [comment]
Thanks for the response @hugoabernier. It turns out I was looking at the wrong github pages:

https://pnp.github.io/sp-dev-fx-extensions/

The samples are not available there.

**Comment by hugoabernier** [comment]
Oh, it looks like the redirect from https://pnp.github.io/sp-dev-fx-extensions/ to aka.ms/spfx-extensions I had put in place isn't working! Good catch!

**Comment by martinlingstuyl** [comment]
So that's it! Nice, now it's completely cleared up!
