### ISSUE TITLE
react-application-personal-assistant - 

### ISSUE THREAD

**Issue by medAmeur-devlopper** [pnp/sp-dev-fx-extensions#923]
### Sample

react-application-personal-assistant

### Author(s)

@anoopt

### What happened?

Hi there,

Thank you for the amazing sample. I have a problem with the app. When I added it to my SharePoint Online website, the virtual assistant button does not appear. Is there anything else I should do or how can I add the app to my website?

I appreciate your help.

### Steps to reproduce

1.package the sample
2.uplod it to the app manager in my sharepoint
3.clikc add to make it with web site

### Expected behavior

its should work as it do on local host

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v14.6

**Comment by anoopt** [comment]
@medAmeur-devlopper - Sorry looks like I missed adding instructions on setting application customiser property. This application customiser needs a property called as `show` which needs to be set to `true`. 

So can you please use this PnP PowerShell cmdlet and set the property?

https://pnp.github.io/powershell/cmdlets/Set-PnPApplicationCustomizer.html

Please see example 2 in that link and use the id as per the sample.

Please let me know if you need more information.

**Comment by hugoabernier** [comment]
@medAmeur-devlopper did @anoopt's instruction help you solve this issue? 

I'll go ahead and close the issue, but please don't hesitate to open a new one if you need more help.

Thanks @anoopt for the fantastic sample, and for always being there to help our community!
